const fs = require('fs');
const path = require('path');

// 1. Docentes Oficiales (35 profesores de las páginas 1, 2, 3 y 4 del PDF oficial)
const DOCENTES_OFICIALES = [
  {
    uid: 'admin_igiffard',
    nombre: 'Dra. Ivone Giffard',
    cargo: 'Subdirectora FCM · Docente de Posgrado',
    titulo_academico: 'Dra.',
    email: 'igiffard@uabc.edu.mx',
    email_normalizado: 'igiffard@uabc.edu.mx',
    role: 'admin',
    programas_asignados_ids: ['MCOC', 'DOC', 'OCE'],
    niveles_asignados: ['posgrado', 'licenciatura'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Subdirección FCM · Biología y Oceanografía',
    cubiculo: 'Edificio 14 (Dirección) · Cubículo Subdirección',
    horario_tutorias: 'Lunes a Viernes 10:00 - 13:00 (Cita previa)',
    telefono_extension: 'Ext. 43102',
    canal_contacto_estudiantes: 'Correo UABC / Teams / Presencial'
  },
  {
    uid: 'prof_bmartin',
    nombre: 'Dr. Benjamín Martín',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'bmartin@uabc.edu.mx',
    email_normalizado: 'bmartin@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Estadística y Modelación',
    cubiculo: 'Edificio 14 · Cubículo 104',
    horario_tutorias: 'Miércoles y Viernes 11:00 - 13:00',
    telefono_extension: 'Ext. 43120',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_llopez',
    nombre: 'Dra. Laura Liliana López Galindo',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'llopez@uabc.edu.mx',
    email_normalizado: 'llopez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biología Molecular y Genética',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 208',
    horario_tutorias: 'Martes y Jueves 10:00 - 12:00',
    telefono_extension: 'Ext. 43215',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_mtorres',
    nombre: 'Dra. Mónica Torres Beltrán',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'mtorres@uabc.edu.mx',
    email_normalizado: 'mtorres@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Bioinformática y Microbiología Marina',
    cubiculo: 'Edificio 14 · Cubículo 108',
    horario_tutorias: 'Lunes y Viernes 13:00 - 15:00',
    telefono_extension: 'Ext. 43118',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_bjuarez',
    nombre: 'Dr. Braulio Juárez A.',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'bjuarez@uabc.edu.mx',
    email_normalizado: 'bjuarez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Oceanografía Física e Hidrodinámica',
    cubiculo: 'Edificio 16 · Cubículo 112',
    horario_tutorias: 'Martes y Jueves 14:00 - 16:00',
    telefono_extension: 'Ext. 43144',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_palvarado',
    nombre: 'Dr. Pedro Alvarado',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'palvarado@uabc.edu.mx',
    email_normalizado: 'palvarado@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica del Océano',
    cubiculo: 'Edificio 16 · Cubículo 115',
    horario_tutorias: 'Martes y Viernes 15:00 - 17:00',
    telefono_extension: 'Ext. 43145',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_stanahara',
    nombre: 'Dra. Sheila Tanahara',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'stanahara@uabc.edu.mx',
    email_normalizado: 'stanahara@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica y Dinámica Oceánica',
    cubiculo: 'Edificio 16 · Cubículo 116',
    horario_tutorias: 'Martes 15:00 - 17:00',
    telefono_extension: 'Ext. 43146',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_eolvera',
    nombre: 'Dr. Eric Olvera',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'eolvera@uabc.edu.mx',
    email_normalizado: 'eolvera@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica y Cómputo Científico',
    cubiculo: 'Edificio 14 · Cubículo 109',
    horario_tutorias: 'Viernes 15:00 - 17:00',
    telefono_extension: 'Ext. 43119',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_nmillan',
    nombre: 'Dr. Norberto Millán',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'nmillan@uabc.edu.mx',
    email_normalizado: 'nmillan@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Seminarios de Investigación',
    cubiculo: 'Edificio 14 (SPD) · Cubículo 102',
    horario_tutorias: 'Lunes 16:00 - 18:00',
    telefono_extension: 'Ext. 43105',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_vfernandez',
    nombre: 'Dr. Víctor Fernández',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'vfernandez@uabc.edu.mx',
    email_normalizado: 'vfernandez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tesis de Posgrado y Oceanografía',
    cubiculo: 'Edificio 18 · Cubículo 205',
    horario_tutorias: 'Martes 17:00 - 19:00',
    telefono_extension: 'Ext. 43160',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_jazepeda',
    nombre: 'Dr. José Alberto Zepeda Domínguez',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jazepeda@uabc.edu.mx',
    email_normalizado: 'jazepeda@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Sistemas Socioecológicos y Manejo Costero',
    cubiculo: 'Edificio 18 · Cubículo 209',
    horario_tutorias: 'Jueves 15:00 - 17:00',
    telefono_extension: 'Ext. 43165',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_jmsandoval',
    nombre: 'Dr. José Miguel Sandoval',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jmsandoval@uabc.edu.mx',
    email_normalizado: 'jmsandoval@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Botánica Marina y Ecofisiología',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 105',
    horario_tutorias: 'Miércoles 17:00 - 19:00',
    telefono_extension: 'Ext. 43220',
    canal_contacto_estudiantes: 'Correo UABC / Meet / Teams'
  },
  {
    uid: 'prof_lenriquez',
    nombre: 'Dra. Lidia Enríquez',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'lenriquez@uabc.edu.mx',
    email_normalizado: 'lenriquez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ecología Molecular y Genética de Poblaciones',
    cubiculo: 'Edificio 56 · Cubículo 101',
    horario_tutorias: 'Martes y Jueves 09:00 - 11:00',
    telefono_extension: 'Ext. 43190',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_hgnava',
    nombre: 'Dr. Héctor García Nava',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'hgnava@uabc.edu.mx',
    email_normalizado: 'hgnava@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Programación y Física Oceanográfica',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 210',
    horario_tutorias: 'Lunes y Viernes 12:00 - 14:00',
    telefono_extension: 'Ext. 43230',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_tolivares',
    nombre: 'Dr. T. Olivares',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'tolivares@uabc.edu.mx',
    email_normalizado: 'tolivares@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biotecnología y Acuacultura',
    cubiculo: 'Edificio 41 · Cubículo 103',
    horario_tutorias: 'Miércoles 12:00 - 14:00',
    telefono_extension: 'Ext. 43180',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_scastellanos',
    nombre: 'Dra. Sara Castellanos',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'scastellanos@uabc.edu.mx',
    email_normalizado: 'scastellanos@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Patología Acuícola y Sanidad Marina',
    cubiculo: 'Edificio 41 · Cubículo 104',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43182',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_ngudino',
    nombre: 'Dr. N. Gudiño',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'ngudino@uabc.edu.mx',
    email_normalizado: 'ngudino@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Morfodinámica Costera y Procesos Litorales',
    cubiculo: 'Edificio 16 · Cubículo 204',
    horario_tutorias: 'Martes y Jueves 13:00 - 15:00',
    telefono_extension: 'Ext. 43150',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_odelrio',
    nombre: 'Dr. Oscar Basilio del Río Zaragoza',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'odelrio@uabc.edu.mx',
    email_normalizado: 'odelrio@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Inmunología y Bioseguridad en Organismos Acuáticos',
    cubiculo: 'Edificio 41 · Cubículo 105',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43185',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_jgcorrea',
    nombre: 'Dr. J.G. Correa',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jgcorrea@uabc.edu.mx',
    email_normalizado: 'jgcorrea@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ingeniería de Sistemas Acuícolas',
    cubiculo: 'Edificio 41 · Cubículo 102',
    horario_tutorias: 'Martes y Jueves 15:00 - 17:00',
    telefono_extension: 'Ext. 43178',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_fbarreto',
    nombre: 'Dr. Fernando Barreto Curiel',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'fbarreto@uabc.edu.mx',
    email_normalizado: 'fbarreto@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Nutrición y Fisiología Acuícola',
    cubiculo: 'Edificio 17 · Cubículo 106',
    horario_tutorias: 'Martes y Jueves 14:00 - 16:00',
    telefono_extension: 'Ext. 43135',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_acastillo',
    nombre: 'Dr. A. Castillo',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'acastillo@uabc.edu.mx',
    email_normalizado: 'acastillo@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Percepción Remota y Óptica Marina',
    cubiculo: 'Edificio 14 · Cubículo 110',
    horario_tutorias: 'Lunes y Viernes 12:00 - 14:00',
    telefono_extension: 'Ext. 43122',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_lmalpica',
    nombre: 'Dr. L. Malpica',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'lmalpica@uabc.edu.mx',
    email_normalizado: 'lmalpica@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ecología Marina y Análisis Cuantitativo en R',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 212',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43235',
    canal_contacto_estudiantes: 'Correo UABC / R-Studio Hub'
  },
  {
    uid: 'prof_mgalaviz',
    nombre: 'Dr. Mario Galaviz',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'mgalaviz@uabc.edu.mx',
    email_normalizado: 'mgalaviz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Bioquímica y Fisiología Digestiva Marina',
    cubiculo: 'Edificio 15 · Cubículo 204',
    horario_tutorias: 'Martes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43128',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_afelix',
    nombre: 'Dr. A. Félix',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'afelix@uabc.edu.mx',
    email_normalizado: 'afelix@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biogeoquímica Marina y Flujos de Carbono',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 108',
    horario_tutorias: 'Viernes 14:00 - 16:00',
    telefono_extension: 'Ext. 43222',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_gsamperio',
    nombre: 'Dr. Guillermo Alberto Samperio Ramos',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'gsamperio@uabc.edu.mx',
    email_normalizado: 'gsamperio@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biogeoquímica Marina y Procesos Costeros',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 110',
    horario_tutorias: 'Viernes 16:00 - 18:00',
    telefono_extension: 'Ext. 43224',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  // Tutores adicionales de la página 4
  {
    uid: 'prof_auribe',
    nombre: 'Dra. Abigail Uribe',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'auribe@uabc.edu.mx',
    email_normalizado: 'auribe@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Marina',
    cubiculo: 'Edificio 18 · Cubículo 202',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43155',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_aabadia',
    nombre: 'Dra. Alicia Abadía',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'aabadia@uabc.edu.mx',
    email_normalizado: 'aabadia@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biología Marina',
    cubiculo: 'Edificio 15 · Cubículo 201',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43126',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_abraga',
    nombre: 'Dr. André Luiz Braga de Souza',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'abraga@uabc.edu.mx',
    email_normalizado: 'abraga@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Oceanografía Costera',
    cubiculo: 'Edificio 16 · Cubículo 206',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43152',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_jvaca',
    nombre: 'Dr. Juan Vaca',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'jvaca@uabc.edu.mx',
    email_normalizado: 'jvaca@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Física Marina',
    cubiculo: 'Edificio 16 · Cubículo 110',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43142',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_klugo',
    nombre: 'Dra. Karina Lugo',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'klugo@uabc.edu.mx',
    email_normalizado: 'klugo@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biogeoquímica',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 106',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43221',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_cdominguez',
    nombre: 'Dr. Carlos Alejandro Domínguez Pérez',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'cdominguez@uabc.edu.mx',
    email_normalizado: 'cdominguez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ciencias Ambientales',
    cubiculo: 'Edificio 18 · Cubículo 208',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43164',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_onorzagaray',
    nombre: 'Dr. Orión Norzagaray',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'onorzagaray@uabc.edu.mx',
    email_normalizado: 'onorzagaray@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Litoral',
    cubiculo: 'Edificio 18 · Cubículo 206',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43162',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_rbeas',
    nombre: 'Dr. Rodrigo Beas',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'rbeas@uabc.edu.mx',
    email_normalizado: 'rbeas@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Marina Submarina',
    cubiculo: 'Edificio 15 · Cubículo 105',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43130',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_mruiz',
    nombre: 'Dra. Mary Carmen Ruíz',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'mruiz@uabc.edu.mx',
    email_normalizado: 'mruiz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biología Celular',
    cubiculo: 'Edificio 15 · Cubículo 203',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43127',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_msantiago',
    nombre: 'Dr. Mauro Wilfrido Santiago García',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'msantiago@uabc.edu.mx',
    email_normalizado: 'msantiago@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías e Hidrodinámica',
    cubiculo: 'Edificio 16 · Cubículo 114',
    horario_tutorias: 'Lunes y Martes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43148',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_rcruz',
    nombre: 'Dr. Ricardo Cruz López',
    cargo: 'Profesor-Investigador · Tutor DCOC',
    titulo_academico: 'Dr.',
    email: 'rcruz@uabc.edu.mx',
    email_normalizado: 'rcruz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Oceanografía Geológica',
    cubiculo: 'Edificio 16 · Cubículo 202',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43154',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  }
];

// 2. Definición exacta de Cursos Oficiales
const CURSOS_OFICIALES = [
  // Grupo 1
  {
    id: 'curso_EST_MULT',
    codigo: 'MCOC-101',
    nombre: 'Estadística Multivariada',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 3,
    horas_laboratorio_semana: 3,
    horas_totales_semana: 6,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_EST_MULT',
    grupo_clave: 'G1',
    profesores_ids: ['prof_bmartin'],
    profesor_nombre: 'Dr. Benjamín Martín',
    sesiones: [
      { dia: 'lunes', hora_inicio: '08:00', hora_fin: '10:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '09:00', hora_fin: '10:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '10:00', hora_fin: '11:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' },
      { dia: 'viernes', hora_inicio: '08:00', hora_fin: '10:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_QPCR',
    codigo: 'MCOC-102',
    nombre: 'Análisis de Expresión Génica en qPCR Tiempo Real',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_QPCR',
    grupo_clave: 'G1',
    profesores_ids: ['prof_llopez'],
    profesor_nombre: 'Dra. Laura Liliana López Galindo',
    sesiones: [
      { dia: 'martes', hora_inicio: '08:00', hora_fin: '10:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'jueves', hora_inicio: '08:00', hora_fin: '10:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_BIOINF',
    codigo: 'MCOC-103',
    nombre: 'Bioinformática',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 3,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 5,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_BIOINF',
    grupo_clave: 'G1',
    profesores_ids: ['prof_mtorres'],
    profesor_nombre: 'Dra. Mónica Torres Beltrán',
    sesiones: [
      { dia: 'lunes', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'viernes', hora_inicio: '10:00', hora_fin: '13:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_HIDRO_EST',
    codigo: 'MCOC-104',
    nombre: 'Introducción a la Hidrodinámica de Estuarios',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 1,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 3,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_HIDRO_EST',
    grupo_clave: 'G1',
    profesores_ids: ['prof_bjuarez'],
    profesor_nombre: 'Dr. Braulio Juárez A.',
    sesiones: [
      { dia: 'martes', hora_inicio: '10:00', hora_fin: '11:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' },
      { dia: 'jueves', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' }
    ]
  },
  {
    id: 'curso_MOD_OCE',
    codigo: 'MCOC-105',
    nombre: 'Modelación Numérica del Océano',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_MOD_OCE',
    grupo_clave: 'G1',
    profesores_ids: ['prof_palvarado', 'prof_stanahara', 'prof_eolvera'],
    profesor_nombre: 'Dr. P. Alvarado, Dra. S. Tanahara, Dr. E. Olvera',
    sesiones: [
      { dia: 'martes', hora_inicio: '13:00', hora_fin: '15:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'viernes', hora_inicio: '13:00', hora_fin: '15:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_SEM_TESIS',
    codigo: 'MCOC-106',
    nombre: 'Seminario de Tesis',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 20,
    grupo_id: 'grupo_G1_SEM_TESIS',
    grupo_clave: 'G1',
    profesores_ids: ['prof_nmillan'],
    profesor_nombre: 'Dr. Norberto Millán',
    sesiones: [
      { dia: 'lunes', hora_inicio: '14:00', hora_fin: '16:00', espacio_id: 'espacio_SPD', aula_codigo: 'E-14 SPD', aula_nombre: 'Sala de Procesamiento de Datos Oceanográficos', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_AVANCE_TESIS_I',
    codigo: 'MCOC-107',
    nombre: 'Avance de Tesis I',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_AVANCE_TESIS_I',
    grupo_clave: 'G1',
    profesores_ids: ['prof_vfernandez'],
    profesor_nombre: 'Dr. Víctor Fernández',
    sesiones: [
      { dia: 'martes', hora_inicio: '15:00', hora_fin: '17:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_AVANCE_TESIS_II',
    codigo: 'MCOC-108',
    nombre: 'Avance de Tesis II',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_AVANCE_TESIS_II',
    grupo_clave: 'G1',
    profesores_ids: ['admin_igiffard'],
    profesor_nombre: 'Dra. Ivone Giffard',
    sesiones: [
      { dia: 'lunes', hora_inicio: '17:00', hora_fin: '19:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_SIST_SOCIOECOL',
    codigo: 'MCOC-109',
    nombre: 'Análisis de sistemas socioecológicos',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G1_SIST_SOCIOECOL',
    grupo_clave: 'G1',
    profesores_ids: ['prof_jazepeda'],
    profesor_nombre: 'Dr. José Alberto Zepeda Domínguez',
    sesiones: [
      { dia: 'jueves', hora_inicio: '17:00', hora_fin: '18:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'jueves', hora_inicio: '18:00', hora_fin: '20:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' },
      { dia: 'viernes', hora_inicio: '20:00', hora_fin: '21:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'practica', tipo_sesion: 'P' }
    ]
  },
  {
    id: 'curso_ECOFIS_MACRO',
    codigo: 'MCOC-110',
    nombre: 'Ecofisiología de Macrófitas Marinas',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 1,
    horas_totales_semana: 3,
    cupo_estimado: 20,
    grupo_id: 'grupo_G1_ECOFIS_MACRO',
    grupo_clave: 'G1',
    profesores_ids: ['prof_jmsandoval'],
    profesor_nombre: 'Dr. José Miguel Sandoval',
    sesiones: [
      { dia: 'miercoles', hora_inicio: '19:00', hora_fin: '21:00', espacio_id: 'espacio_VIR', aula_codigo: 'VIR', aula_nombre: 'Modalidad Virtual', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '21:00', hora_fin: '22:00', espacio_id: 'espacio_VIR', aula_codigo: 'VIR', aula_nombre: 'Modalidad Virtual', tipo_componente: 'laboratorio', tipo_sesion: 'L' }
    ]
  },

  // Grupo 2
  {
    id: 'curso_ECOL_MOL',
    codigo: 'MCOC-201',
    nombre: 'Ecología Molecular',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 30,
    grupo_id: 'grupo_G2_ECOL_MOL',
    grupo_clave: 'G2',
    profesores_ids: ['prof_lenriquez'],
    profesor_nombre: 'Dra. Lidia Enríquez',
    sesiones: [
      { dia: 'martes', hora_inicio: '07:00', hora_fin: '09:00', espacio_id: 'espacio_TOA', aula_codigo: 'E-56 TOA', aula_nombre: 'Salón Totoaba A', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'jueves', hora_inicio: '07:00', hora_fin: '09:00', espacio_id: 'espacio_TOA', aula_codigo: 'E-56 TOA', aula_nombre: 'Salón Totoaba A', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_AVANCE_TESIS_III',
    codigo: 'MCOC-202',
    nombre: 'Avance de Tesis III',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 30,
    grupo_id: 'grupo_G2_AVANCE_TESIS_III',
    grupo_clave: 'G2',
    profesores_ids: ['prof_lenriquez'],
    profesor_nombre: 'Dra. Lidia Enríquez',
    sesiones: [
      { dia: 'miercoles', hora_inicio: '07:00', hora_fin: '09:00', espacio_id: 'espacio_TOA', aula_codigo: 'E-56 TOA', aula_nombre: 'Salón Totoaba A', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_PROGRAMACION',
    codigo: 'MCOC-203',
    nombre: 'Programación',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 1,
    horas_totales_semana: 3,
    cupo_estimado: 25,
    grupo_id: 'grupo_G2_PROGRAMACION',
    grupo_clave: 'G2',
    profesores_ids: ['prof_hgnava'],
    profesor_nombre: 'Dr. Héctor García Nava',
    sesiones: [
      { dia: 'lunes', hora_inicio: '10:00', hora_fin: '11:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'viernes', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_SEM_ACUACULTURA',
    codigo: 'MCOC-204',
    nombre: 'Seminario de Acuacultura',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 20,
    grupo_id: 'grupo_G2_SEM_ACUACULTURA',
    grupo_clave: 'G2',
    profesores_ids: ['prof_tolivares', 'prof_scastellanos'],
    profesor_nombre: 'Dr. T. Olivares y Dra. S. Castellanos',
    sesiones: [
      { dia: 'miercoles', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_VIR', aula_codigo: 'VIR', aula_nombre: 'Modalidad Virtual', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_PROC_LITORALES',
    codigo: 'MCOC-205',
    nombre: 'Procesos Litorales y Manejo de la Erosión Costera',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 0,
    horas_laboratorio_semana: 4,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G2_PROC_LITORALES',
    grupo_clave: 'G2',
    profesores_ids: ['prof_ngudino'],
    profesor_nombre: 'Dr. N. Gudiño',
    sesiones: [
      { dia: 'martes', hora_inicio: '11:00', hora_fin: '13:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'jueves', hora_inicio: '10:00', hora_fin: '11:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'martes', hora_inicio: '17:00', hora_fin: '18:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (Espacio por definir)', tipo_componente: 'practica', tipo_sesion: 'P' }
    ]
  },
  {
    id: 'curso_PAT_BIOSEG',
    codigo: 'MCOC-206',
    nombre: 'Patología y Bioseguridad Acuícola',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G2_PAT_BIOSEG',
    grupo_clave: 'G2',
    profesores_ids: ['prof_odelrio', 'prof_scastellanos'],
    profesor_nombre: 'Dr. O. del Río y Dra. S. Castellanos',
    sesiones: [
      { dia: 'lunes', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_SIST_ACUA',
    codigo: 'MCOC-207',
    nombre: 'Sistemas en Acuacultura',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 3,
    horas_laboratorio_semana: 1,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G2_SIST_ACUA',
    grupo_clave: 'G2',
    profesores_ids: ['prof_jgcorrea', 'prof_fbarreto'],
    profesor_nombre: 'Dr. J.G. Correa y Dr. Fernando Barreto',
    sesiones: [
      { dia: 'martes', hora_inicio: '13:00', hora_fin: '15:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'teoria', tipo_sesion: 'T' },
      { dia: 'jueves', hora_inicio: '12:00', hora_fin: '13:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'jueves', hora_inicio: '13:00', hora_fin: '14:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },

  // Grupo 3
  {
    id: 'curso_COLOR_OCEANO',
    codigo: 'MCOC-301',
    nombre: 'Temas Selectos de Percepción Remota del Color del Océano',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 15,
    grupo_id: 'grupo_G3_COLOR_OCEANO',
    grupo_clave: 'G3',
    profesores_ids: ['prof_acastillo'],
    profesor_nombre: 'Dr. A. Castillo',
    sesiones: [
      { dia: 'lunes', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_SA', aula_codigo: 'E-14 SA', aula_nombre: 'Salón de Asesorías', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'viernes', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_SA', aula_codigo: 'E-14 SA', aula_nombre: 'Salón de Asesorías', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_ECOL_R',
    codigo: 'MCOC-302',
    nombre: 'Ecological Data in R',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 2,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G3_ECOL_R',
    grupo_clave: 'G3',
    profesores_ids: ['prof_lmalpica'],
    profesor_nombre: 'Dr. L. Malpica',
    sesiones: [
      { dia: 'lunes', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '10:00', hora_fin: '12:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_BIOQ_NUT_ACU',
    codigo: 'MCOC-303',
    nombre: 'Bioquímica Nutricional Acuícola',
    tipo_actividad: 'mixto',
    horas_teoria_semana: 0,
    horas_laboratorio_semana: 4,
    horas_totales_semana: 4,
    cupo_estimado: 25,
    grupo_id: 'grupo_G3_BIOQ_NUT_ACU',
    grupo_clave: 'G3',
    profesores_ids: ['prof_mgalaviz', 'prof_fbarreto'],
    profesor_nombre: 'Dr. Mario Galaviz y Dr. Fernando Barreto',
    sesiones: [
      { dia: 'martes', hora_inicio: '11:00', hora_fin: '13:00', espacio_id: 'espacio_CPB', aula_codigo: 'E-14 CPB', aula_nombre: 'Centro de Cómputo de Posgrado, Sala B', tipo_componente: 'laboratorio', tipo_sesion: 'C' },
      { dia: 'miercoles', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_SP1', aula_codigo: 'E-25 SP1', aula_nombre: 'Salón de Posgrado 1 (IIO)', tipo_componente: 'laboratorio', tipo_sesion: 'C' }
    ]
  },
  {
    id: 'curso_SEM_BIOGEOQUIM',
    codigo: 'MCOC-304',
    nombre: 'Seminario de Biogeoquímica Acuática Avanzado',
    tipo_actividad: 'seminario',
    horas_teoria_semana: 4,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 4,
    cupo_estimado: 45,
    grupo_id: 'grupo_G3_SEM_BIOGEOQUIM',
    grupo_clave: 'G3',
    profesores_ids: ['prof_afelix', 'prof_gsamperio'],
    profesor_nombre: 'Dr. A. Félix y Dr. Guillermo Samperio',
    sesiones: [
      { dia: 'viernes', hora_inicio: '12:00', hora_fin: '14:00', espacio_id: 'espacio_AVI', aula_codigo: 'E-25 AVI', aula_nombre: 'Audiovisual IIO', tipo_componente: 'seminario', tipo_sesion: 'T' },
      { dia: 'viernes', hora_inicio: '14:00', hora_fin: '16:00', espacio_id: 'espacio_AVI', aula_codigo: 'E-25 AVI', aula_nombre: 'Audiovisual IIO', tipo_componente: 'seminario', tipo_sesion: 'T' }
    ]
  },

  // Tutorías Académicas (Página 4)
  {
    id: 'curso_TUTORIA_A',
    codigo: 'POS-TUT-A',
    nombre: 'Tutoría Académica (Grupo A)',
    tipo_actividad: 'direccion_tutorial',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 25,
    grupo_id: 'grupo_TUTORIA_A',
    grupo_clave: 'Tut-A',
    profesores_ids: ['prof_auribe', 'prof_aabadia', 'prof_abraga', 'prof_bjuarez', 'prof_fbarreto', 'prof_hgnava', 'prof_jvaca', 'prof_klugo', 'prof_llopez', 'prof_cdominguez', 'prof_onorzagaray', 'prof_odelrio', 'prof_rbeas', 'prof_jazepeda', 'prof_jmsandoval', 'prof_mgalaviz', 'prof_mruiz', 'prof_mtorres', 'prof_msantiago', 'prof_rcruz', 'prof_gsamperio'],
    profesor_nombre: 'Claustro de Tutores MCOC/DCOC (Grupo A)',
    sesiones: [
      { dia: 'lunes', hora_inicio: '19:00', hora_fin: '21:00', espacio_id: 'espacio_VIR', aula_codigo: 'VIR', aula_nombre: 'Modalidad Virtual (Sesión Tutorial A)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  },
  {
    id: 'curso_TUTORIA_B',
    codigo: 'POS-TUT-B',
    nombre: 'Tutoría Académica (Grupo B)',
    tipo_actividad: 'direccion_tutorial',
    horas_teoria_semana: 2,
    horas_laboratorio_semana: 0,
    horas_totales_semana: 2,
    cupo_estimado: 10,
    grupo_id: 'grupo_TUTORIA_B',
    grupo_clave: 'Tut-B',
    profesores_ids: ['prof_bjuarez', 'prof_msantiago', 'prof_fbarreto', 'prof_jazepeda'],
    profesor_nombre: 'Claustro de Tutores MCOC/DCOC (Grupo B)',
    sesiones: [
      { dia: 'martes', hora_inicio: '19:00', hora_fin: '21:00', espacio_id: 'espacio_VIR', aula_codigo: 'VIR', aula_nombre: 'Modalidad Virtual (Sesión Tutorial B)', tipo_componente: 'teoria', tipo_sesion: 'T' }
    ]
  }
];

// 3. Estudiantes y Asignación de Tutores Oficiales (Página 4 del PDF)
const TUTORIAS_ESTUDIANTES = [
  // Grupo A: Lunes 7-9 pm VIR
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Isabel Quesada Ávila', tutor_nombre: 'Dra. Abigail Uribe', tutor_id: 'prof_auribe', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Sebastián Ruiz Mejía', tutor_nombre: 'Dra. Alicia Abadía', tutor_id: 'prof_aabadia', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Emilio Moreno Garnelo', tutor_nombre: 'Dr. André Luiz Braga de Souza', tutor_id: 'prof_abraga', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Angélica San Pedro Granados', tutor_nombre: 'Dr. Braulio Juárez A.', tutor_id: 'prof_bjuarez', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Ulysses Guillermo Miramontes Salcedo', tutor_nombre: 'Dr. Fernando Barreto', tutor_id: 'prof_fbarreto', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Marshall Díaz Londoño', tutor_nombre: 'Dr. Héctor García Nava', tutor_id: 'prof_hgnava', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Ana Nicole Magaña Sánchez', tutor_nombre: 'Dr. Juan Vaca', tutor_id: 'prof_jvaca', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Iván Córdova Medina', tutor_nombre: 'Dra. Karina Lugo', tutor_id: 'prof_klugo', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Raúl Rivera Herrera', tutor_nombre: 'Dra. Laura Liliana López Galindo', tutor_id: 'prof_llopez', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Daniela Soltero Rosales', tutor_nombre: 'Dr. Carlos Alejandro Domínguez Pérez', tutor_id: 'prof_cdominguez', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Luis Ramón Rodríguez León', tutor_nombre: 'Dr. Orión Norzagaray', tutor_id: 'prof_onorzagaray', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Fátima del Rocío Balcázar Jiménez', tutor_nombre: 'Dr. Oscar del Río', tutor_id: 'prof_odelrio', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Víctor Manuel Sánchez Franco', tutor_nombre: 'Dr. Rodrigo Beas', tutor_id: 'prof_rbeas', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'José Pablo Morelos Padilla', tutor_nombre: 'Dr. José Alberto Zepeda', tutor_id: 'prof_jazepeda', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Kenia Elizabeth Borbón Fuentes', tutor_nombre: 'Dr. José Miguel Sandoval', tutor_id: 'prof_jmsandoval', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Gustavo Alexis Cárdenas López', tutor_nombre: 'Dr. Mario Galaviz', tutor_id: 'prof_mgalaviz', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Itzel Mariana Salas Rodela', tutor_nombre: 'Dra. Mary Carmen Ruíz', tutor_id: 'prof_mruiz', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Martha Itzel Parada Espinoza', tutor_nombre: 'Dra. Mónica Torres Beltrán', tutor_id: 'prof_mtorres', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Carlos Alejandro Domínguez Pérez', tutor_nombre: 'Dr. Mauro Wilfrido Santiago García', tutor_id: 'prof_msantiago', nivel: 'Tutoría Académica I' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Andrea Itzel Munguía Casillas', tutor_nombre: 'Dr. Oscar Basilio del Río Zaragoza', tutor_id: 'prof_odelrio', nivel: 'Tutoría Académica II' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Michelle Fimbres Martínez', tutor_nombre: 'Dr. Ricardo Cruz López', tutor_id: 'prof_rcruz', nivel: 'Tutoría Académica II' },
  { grupo: 'A', dia: 'Lunes 19:00 - 21:00', estudiante: 'Wilson Alberto Solís Turbequia', tutor_nombre: 'Dr. Guillermo Alberto Samperio Ramos', tutor_id: 'prof_gsamperio', nivel: 'Tutoría Académica II' },

  // Grupo B: Martes 7-9 pm VIR
  { grupo: 'B', dia: 'Martes 19:00 - 21:00', estudiante: 'Daniela Rubí Galván Ramos', tutor_nombre: 'Dr. Braulio Juárez A.', tutor_id: 'prof_bjuarez', nivel: 'Tutoría Académica I' },
  { grupo: 'B', dia: 'Martes 19:00 - 21:00', estudiante: 'Kendra Danielle Mora Giles', tutor_nombre: 'Dr. Mauro Wilfrido Santiago García', tutor_id: 'prof_msantiago', nivel: 'Tutoría Académica I' },
  { grupo: 'B', dia: 'Martes 19:00 - 21:00', estudiante: 'Aldo Emmanuel Belmonte Romo', tutor_nombre: 'Dr. Fernando Barreto Curiel', tutor_id: 'prof_fbarreto', nivel: 'Tutoría Académica I' },
  { grupo: 'B', dia: 'Martes 19:00 - 21:00', estudiante: 'Camila Alejandra Reyes Rincón', tutor_nombre: 'Dr. José Alberto Zepeda Dominguez', tutor_id: 'prof_jazepeda', nivel: 'Tutoría Académica II' }
];

console.log('Total asignaciones tutoriales estudiantes:', TUTORIAS_ESTUDIANTES.length);

module.exports = {
  DOCENTES_OFICIALES,
  CURSOS_OFICIALES,
  TUTORIAS_ESTUDIANTES
};
