const fs = require('fs');
const path = require('path');

// 1. Catálogo Exacto de Docentes Oficiales (según PDF páginas 1, 2, 3 y 4)
const DOCENTES_OFICIALES = [
  {
    uid: 'admin_igiffard',
    nombre: 'Dra. Ivone Giffard',
    cargo: 'Subdirectora FCM · Docente de Posgrado',
    titulo_academico: 'Dra.',
    email: 'igiffard@uabc.edu.mx',
    email_normalizado: 'igiffard@uabc.edu.mx',
    role: 'admin',
    programas_asignados_ids: ['MCOC', 'DOC', 'OCE'],
    niveles_asignados: ['posgrado', 'licenciatura'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Subdirección FCM · Biología y Oceanografía',
    cubiculo: 'Edificio 14 (Dirección) · Cubículo Subdirección',
    horario_tutorias: 'Lunes a Viernes 10:00 - 13:00 (Cita previa)',
    telefono_extension: 'Ext. 43102',
    canal_contacto_estudiantes: 'Correo UABC / Teams / Presencial'
  },
  {
    uid: 'prof_bmartin',
    nombre: 'Dr. Benjamín Martín',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'bmartin@uabc.edu.mx',
    email_normalizado: 'bmartin@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Estadística y Modelación',
    cubiculo: 'Edificio 14 · Cubículo 104',
    horario_tutorias: 'Miércoles y Viernes 11:00 - 13:00',
    telefono_extension: 'Ext. 43120',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_llopez',
    nombre: 'Dra. Laura Liliana López Galindo',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'llopez@uabc.edu.mx',
    email_normalizado: 'llopez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biología Molecular y Genética',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 208',
    horario_tutorias: 'Martes y Jueves 10:00 - 12:00',
    telefono_extension: 'Ext. 43215',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_mtorres',
    nombre: 'Dra. Mónica Torres Beltrán',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'mtorres@uabc.edu.mx',
    email_normalizado: 'mtorres@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Bioinformática y Microbiología Marina',
    cubiculo: 'Edificio 14 · Cubículo 108',
    horario_tutorias: 'Lunes y Viernes 13:00 - 15:00',
    telefono_extension: 'Ext. 43118',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_bjuarez',
    nombre: 'Dr. Braulio Juárez A.',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'bjuarez@uabc.edu.mx',
    email_normalizado: 'bjuarez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Oceanografía Física e Hidrodinámica',
    cubiculo: 'Edificio 16 · Cubículo 112',
    horario_tutorias: 'Martes y Jueves 14:00 - 16:00',
    telefono_extension: 'Ext. 43144',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_palvarado',
    nombre: 'Dr. Pedro Alvarado',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'palvarado@uabc.edu.mx',
    email_normalizado: 'palvarado@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica del Océano',
    cubiculo: 'Edificio 16 · Cubículo 115',
    horario_tutorias: 'Martes y Viernes 15:00 - 17:00',
    telefono_extension: 'Ext. 43145',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_stanahara',
    nombre: 'Dra. Sheila Tanahara',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'stanahara@uabc.edu.mx',
    email_normalizado: 'stanahara@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica y Dinámica Oceánica',
    cubiculo: 'Edificio 16 · Cubículo 116',
    horario_tutorias: 'Martes 15:00 - 17:00',
    telefono_extension: 'Ext. 43146',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_eolvera',
    nombre: 'Dr. Eric Olvera',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'eolvera@uabc.edu.mx',
    email_normalizado: 'eolvera@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Modelación Numérica y Cómputo Científico',
    cubiculo: 'Edificio 14 · Cubículo 109',
    horario_tutorias: 'Viernes 15:00 - 17:00',
    telefono_extension: 'Ext. 43119',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_nmillan',
    nombre: 'Dr. Norberto Millán',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'nmillan@uabc.edu.mx',
    email_normalizado: 'nmillan@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Seminarios de Investigación',
    cubiculo: 'Edificio 14 (SPD) · Cubículo 102',
    horario_tutorias: 'Lunes 16:00 - 18:00',
    telefono_extension: 'Ext. 43105',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_vfernandez',
    nombre: 'Dr. Víctor Fernández',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'vfernandez@uabc.edu.mx',
    email_normalizado: 'vfernandez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tesis de Posgrado y Oceanografía',
    cubiculo: 'Edificio 18 · Cubículo 205',
    horario_tutorias: 'Martes 17:00 - 19:00',
    telefono_extension: 'Ext. 43160',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_jazepeda',
    nombre: 'Dr. José Alberto Zepeda Domínguez',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jazepeda@uabc.edu.mx',
    email_normalizado: 'jazepeda@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Sistemas Socioecológicos y Manejo Costero',
    cubiculo: 'Edificio 18 · Cubículo 209',
    horario_tutorias: 'Jueves 15:00 - 17:00',
    telefono_extension: 'Ext. 43165',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_jmsandoval',
    nombre: 'Dr. José Miguel Sandoval',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jmsandoval@uabc.edu.mx',
    email_normalizado: 'jmsandoval@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Botánica Marina y Ecofisiología',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 105',
    horario_tutorias: 'Miércoles 17:00 - 19:00',
    telefono_extension: 'Ext. 43220',
    canal_contacto_estudiantes: 'Correo UABC / Meet / Teams'
  },
  {
    uid: 'prof_lenriquez',
    nombre: 'Dra. Lidia Enríquez',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'lenriquez@uabc.edu.mx',
    email_normalizado: 'lenriquez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ecología Molecular y Genética de Poblaciones',
    cubiculo: 'Edificio 56 · Cubículo 101',
    horario_tutorias: 'Martes y Jueves 09:00 - 11:00',
    telefono_extension: 'Ext. 43190',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_hgnava',
    nombre: 'Dr. Héctor García Nava',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'hgnava@uabc.edu.mx',
    email_normalizado: 'hgnava@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Programación y Física Oceanográfica',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 210',
    horario_tutorias: 'Lunes y Viernes 12:00 - 14:00',
    telefono_extension: 'Ext. 43230',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_tolivares',
    nombre: 'Dr. T. Olivares',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'tolivares@uabc.edu.mx',
    email_normalizado: 'tolivares@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biotecnología y Acuacultura',
    cubiculo: 'Edificio 41 · Cubículo 103',
    horario_tutorias: 'Miércoles 12:00 - 14:00',
    telefono_extension: 'Ext. 43180',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_scastellanos',
    nombre: 'Dra. Sara Castellanos',
    cargo: 'Profesora-Investigadora',
    titulo_academico: 'Dra.',
    email: 'scastellanos@uabc.edu.mx',
    email_normalizado: 'scastellanos@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Patología Acuícola y Sanidad Marina',
    cubiculo: 'Edificio 41 · Cubículo 104',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43182',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_ngudino',
    nombre: 'Dr. N. Gudiño',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'ngudino@uabc.edu.mx',
    email_normalizado: 'ngudino@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Morfodinámica Costera y Procesos Litorales',
    cubiculo: 'Edificio 16 · Cubículo 204',
    horario_tutorias: 'Martes y Jueves 13:00 - 15:00',
    telefono_extension: 'Ext. 43150',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_odelrio',
    nombre: 'Dr. Oscar Basilio del Río Zaragoza',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'odelrio@uabc.edu.mx',
    email_normalizado: 'odelrio@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Inmunología y Bioseguridad en Organismos Acuáticos',
    cubiculo: 'Edificio 41 · Cubículo 105',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43185',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_jgcorrea',
    nombre: 'Dr. J.G. Correa',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'jgcorrea@uabc.edu.mx',
    email_normalizado: 'jgcorrea@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ingeniería de Sistemas Acuícolas',
    cubiculo: 'Edificio 41 · Cubículo 102',
    horario_tutorias: 'Martes y Jueves 15:00 - 17:00',
    telefono_extension: 'Ext. 43178',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_fbarreto',
    nombre: 'Dr. Fernando Barreto Curiel',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'fbarreto@uabc.edu.mx',
    email_normalizado: 'fbarreto@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Nutrición y Fisiología Acuícola',
    cubiculo: 'Edificio 17 · Cubículo 106',
    horario_tutorias: 'Martes y Jueves 14:00 - 16:00',
    telefono_extension: 'Ext. 43135',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_acastillo',
    nombre: 'Dr. A. Castillo',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'acastillo@uabc.edu.mx',
    email_normalizado: 'acastillo@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Percepción Remota y Óptica Marina',
    cubiculo: 'Edificio 14 · Cubículo 110',
    horario_tutorias: 'Lunes y Viernes 12:00 - 14:00',
    telefono_extension: 'Ext. 43122',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_lmalpica',
    nombre: 'Dr. L. Malpica',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'lmalpica@uabc.edu.mx',
    email_normalizado: 'lmalpica@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Ecología Marina y Análisis Cuantitativo en R',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 212',
    horario_tutorias: 'Lunes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43235',
    canal_contacto_estudiantes: 'Correo UABC / R-Studio Hub'
  },
  {
    uid: 'prof_mgalaviz',
    nombre: 'Dr. Mario Galaviz',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'mgalaviz@uabc.edu.mx',
    email_normalizado: 'mgalaviz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Bioquímica y Fisiología Digestiva Marina',
    cubiculo: 'Edificio 15 · Cubículo 204',
    horario_tutorias: 'Martes y Miércoles 14:00 - 16:00',
    telefono_extension: 'Ext. 43128',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_afelix',
    nombre: 'Dr. A. Félix',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'afelix@uabc.edu.mx',
    email_normalizado: 'afelix@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biogeoquímica Marina y Flujos de Carbono',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 108',
    horario_tutorias: 'Viernes 14:00 - 16:00',
    telefono_extension: 'Ext. 43222',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  {
    uid: 'prof_gsamperio',
    nombre: 'Dr. Guillermo Alberto Samperio Ramos',
    cargo: 'Profesor-Investigador',
    titulo_academico: 'Dr.',
    email: 'gsamperio@uabc.edu.mx',
    email_normalizado: 'gsamperio@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Biogeoquímica Marina y Procesos Costeros',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 110',
    horario_tutorias: 'Viernes 16:00 - 18:00',
    telefono_extension: 'Ext. 43224',
    canal_contacto_estudiantes: 'Correo UABC'
  },
  // Tutores adicionales de la página 4
  {
    uid: 'prof_auribe',
    nombre: 'Dra. Abigail Uribe',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'auribe@uabc.edu.mx',
    email_normalizado: 'auribe@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Marina',
    cubiculo: 'Edificio 18 · Cubículo 202',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43155',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_aabadia',
    nombre: 'Dra. Alicia Abadía',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'aabadia@uabc.edu.mx',
    email_normalizado: 'aabadia@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biología Marina',
    cubiculo: 'Edificio 15 · Cubículo 201',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43126',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_abraga',
    nombre: 'Dr. André Luiz Braga de Souza',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'abraga@uabc.edu.mx',
    email_normalizado: 'abraga@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Oceanografía Costera',
    cubiculo: 'Edificio 16 · Cubículo 206',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43152',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_jvaca',
    nombre: 'Dr. Juan Vaca',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'jvaca@uabc.edu.mx',
    email_normalizado: 'jvaca@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Física Marina',
    cubiculo: 'Edificio 16 · Cubículo 110',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43142',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_klugo',
    nombre: 'Dra. Karina Lugo',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'klugo@uabc.edu.mx',
    email_normalizado: 'klugo@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biogeoquímica',
    cubiculo: 'Edificio 25 (IIO) · Cubículo 106',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43221',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_cdominguez',
    nombre: 'Dr. Carlos Alejandro Domínguez Pérez',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'cdominguez@uabc.edu.mx',
    email_normalizado: 'cdominguez@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ciencias Ambientales',
    cubiculo: 'Edificio 18 · Cubículo 208',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43164',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_onorzagaray',
    nombre: 'Dr. Orión Norzagaray',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'onorzagaray@uabc.edu.mx',
    email_normalizado: 'onorzagaray@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Litoral',
    cubiculo: 'Edificio 18 · Cubículo 206',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43162',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_rbeas',
    nombre: 'Dr. Rodrigo Beas',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'rbeas@uabc.edu.mx',
    email_normalizado: 'rbeas@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Ecología Marina Submarina',
    cubiculo: 'Edificio 15 · Cubículo 105',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43130',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_mruiz',
    nombre: 'Dra. Mary Carmen Ruíz',
    cargo: 'Profesora-Investigadora · Tutora MCOC',
    titulo_academico: 'Dra.',
    email: 'mruiz@uabc.edu.mx',
    email_normalizado: 'mruiz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Biología Celular',
    cubiculo: 'Edificio 15 · Cubículo 203',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43127',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_msantiago',
    nombre: 'Dr. Mauro Wilfrido Santiago García',
    cargo: 'Profesor-Investigador · Tutor MCOC',
    titulo_academico: 'Dr.',
    email: 'msantiago@uabc.edu.mx',
    email_normalizado: 'msantiago@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías e Hidrodinámica',
    cubiculo: 'Edificio 16 · Cubículo 114',
    horario_tutorias: 'Lunes y Martes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43148',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  },
  {
    uid: 'prof_rcruz',
    nombre: 'Dr. Ricardo Cruz López',
    cargo: 'Profesor-Investigador · Tutor DCOC',
    titulo_academico: 'Dr.',
    email: 'rcruz@uabc.edu.mx',
    email_normalizado: 'rcruz@uabc.edu.mx',
    role: 'profesor',
    programas_asignados_ids: ['MCOC', 'DOC'],
    niveles_asignados: ['posgrado'],
    activo: true,
    origen_pdf_posgrado: true,
    academia_area: 'Tutorías y Oceanografía Geológica',
    cubiculo: 'Edificio 16 · Cubículo 202',
    horario_tutorias: 'Lunes 19:00 - 21:00 (VIR)',
    telefono_extension: 'Ext. 43154',
    canal_contacto_estudiantes: 'Correo UABC / Teams'
  }
];

console.log('Total docentes oficiales:', DOCENTES_OFICIALES.length);
